using System.Collections.Generic;
using wotr_mod.Infrastructure;

namespace wotr_mod.Content.Localization
{
    internal static class ModText
    {
        private static readonly Dictionary<string, string> Strings = new Dictionary<string, string>
        {
            { LocalizationIds.Game.AnimalCompanionLeopardDescription, "{g|Encyclopedia:Size}Size{/g}: Small\n{g|Encyclopedia:Speed}Speed{/g}: 50 ft.\n{g|Encyclopedia:Armor_Class}AC{/g}: +4 natural armor\n{g|Encyclopedia:Attack}Attacks{/g}: bite ({g|Encyclopedia:Dice}1d4{/g} plus trip), 2 claws (1d2)\n{g|Encyclopedia:Ability_Scores}Ability scores{/g}: {g|Encyclopedia:Strength}Str{/g} 12, {g|Encyclopedia:Dexterity}Dex{/g} 21, {g|Encyclopedia:Constitution}Con{/g} 13, {g|Encyclopedia:Intelligence}Int{/g} 2, {g|Encyclopedia:Wisdom}Wis{/g} 12, {g|Encyclopedia:Charisma}Cha{/g} 6\nSpecial qualities: {g|Encyclopedia:Scent}scent{/g}.\nAt 4th level, a leopard's size becomes Medium and it gains Str +4, Dex -2, Con +2, and the {g|FeaturePounce}pounce{/g} ability.\nSneak Attack: A leopard deals an additional 1d6 precision {g|Encyclopedia:Damage}damage{/g} to {g|Encyclopedia:Flat_Footed}flat-footed{/g} or {g|Encyclopedia:Flanking}flanked{/g} targets (2d6 at 4th level)." },
            { LocalizationIds.Game.AnimalCompanionVelociraptorDescription, "{g|Encyclopedia:Size}Size{/g}: Small\n{g|Encyclopedia:Speed}Speed{/g}: 60 ft.\n{g|Encyclopedia:Armor_Class}AC{/g}: +3 natural armor\n{g|Encyclopedia:Attack}Attacks{/g}: bite ({g|Encyclopedia:Dice}1d4{/g}), 2 talons (1d6)\n{g|Encyclopedia:Ability_Scores}Ability scores{/g}: {g|Encyclopedia:Strength}Str{/g} 11, {g|Encyclopedia:Dexterity}Dex{/g} 17, {g|Encyclopedia:Constitution}Con{/g} 17, {g|Encyclopedia:Intelligence}Int{/g} 2, {g|Encyclopedia:Wisdom}Wis{/g} 12, {g|Encyclopedia:Charisma}Cha{/g} 14\nSpecial qualities: {g|Encyclopedia:Scent}scent{/g}.\nAt 4th level, a velociraptor's size becomes Medium and it gains Str +4, Dex -2, Con +2, +2 to its natural armor {g|Encyclopedia:Bonus}bonus{/g} to AC, and the {g|FeaturePounce}pounce{/g} ability.\nAgile Movement: A velociraptor can move through {g|Encyclopedia:Threatened_Area}threatened areas{/g} without provoking {g|Encyclopedia:Attack_Of_Opportunity}attacks of opportunity{/g}." },
            { LocalizationIds.Mod.CleverPyromaniacName, "Clever Pyromaniac" },
            { LocalizationIds.Mod.CleverPyromaniacDescription, "These gnomes are as dangerously fascinated by fire as pyromaniacs, but their experiments sharpen the mind instead of charm. They gain the Pyromaniac heritage benefits and replace the gnome racial +2 Charisma bonus with +3 Intelligence and Wisdom, and a +2 Constitution bonus." },
            { LocalizationIds.Mod.UmbralDhampirHeritageName, "Umbral Dhampir" },
            { LocalizationIds.Mod.UmbralDhampirHeritageDescription, "These dhampirs carry an unusually deep shadow in their blood. They gain a +3 racial bonus to Charisma, a +3 racial bonus to Dexterity, and a +2 racial bonus to Constitution." },
            { LocalizationIds.Mod.CryptguardDhampirHeritageName, "Cryptguard" },
            { LocalizationIds.Mod.CryptguardDhampirHeritageDescription, "These dhampirs are born to be guardians of the dead, possessing unnatural strength. They gain a +3 racial bonus to Strength, a +2 racial bonus to Dexterity, and a +3 racial bonus to Charisma." },
            { LocalizationIds.Mod.GraveltoeGnomeHeritageName, "Graveltoe Gnome" },
            { LocalizationIds.Mod.GraveltoeGnomeHeritageDescription, "These gnomes are charming, and have the strength of the earth. They gain a +3 racial bonus to Charisma, a +2 racial bonus to Constitution, and a +3 racial bonus to Strength." },
            { LocalizationIds.Mod.ShadowGnomeHeritageName, "Fae-Blood Gnome" },
            { LocalizationIds.Mod.ShadowGnomeHeritageDescription, "These gnomes move like living silhouettes, charming and elusive. They gain +3 racial bonuses to Charisma and Dexterity and a +2 racial bonus to Constitution." },
            { LocalizationIds.Mod.HumanHeritageName, "Human Heritage" },
            { LocalizationIds.Mod.HumanHeritageDescription, "The circumstances of a human's birth and ancestry can shape their natural gifts." },
            { LocalizationIds.Mod.NormalHumanHeritageName, "Normal" },
            { LocalizationIds.Mod.NormalHumanHeritageDescription, "These humans follow the standard human heritage." },
            { LocalizationIds.Mod.DescendantOfKingsHeritageName, "Descendant of Kings" },
            { LocalizationIds.Mod.DescendantOfKingsHeritageDescription, "These humans descend from old lines of rulers and conquerors. They gain a +2 racial bonus to Constitution, and their selectable human ability score bonus increases from +2 to +4." },
            { LocalizationIds.Mod.OrcLordsBloodHeritageName, "Orc Lords Blood" },
            { LocalizationIds.Mod.OrcLordsBloodHeritageDescription, "These half-orcs carry the blood of ancient warlords. They gain a +2 racial bonus to Constitution, and their selectable half-orc ability score bonus increases from +2 to +4." },
            { LocalizationIds.Mod.TrueHighElfHeritageName, "True High Elf" },
            { LocalizationIds.Mod.TrueHighElfHeritageDescription, "These half-elves are touched by an old and potent elven lineage. They gain a +2 racial bonus to Constitution, and their selectable half-elf ability score bonus increases from +2 to +4." },
            { LocalizationIds.Mod.FetchlingHeritageName, "Fetchling Heritage" },
            { LocalizationIds.Mod.FetchlingHeritageDescription, "Fetchlings carry the influence of the Shadow Plane in their blood, which can manifest in different ways." },
            { LocalizationIds.Mod.DefaultFetchlingHeritageName, "Fetchling" },
            { LocalizationIds.Mod.DefaultFetchlingHeritageDescription, "Standard fetchlings are quick and perceptive, with an affinity for shadow magic. They gain a +3 racial bonus to Dexterity, a +3 racial bonus to Charisma, and a +2 racial bonus to Constitution." },
            { LocalizationIds.Mod.ShadowWarriorFetchlingHeritageName, "Shadow Warrior" },
            { LocalizationIds.Mod.ShadowWarriorFetchlingHeritageDescription, "Shadow Warriors are fetchlings who have embraced the physical might latent in their shadow heritage, trading quickness for raw strength. They gain a +3 racial bonus to Strength, a +3 racial bonus to Charisma, and a +2 racial bonus to Constitution." },
            { LocalizationIds.Mod.CompanionPetName, "Companion Pet" },
            { LocalizationIds.Mod.CompanionPetDescription, "Select an animal companion." },
            { LocalizationIds.Mod.NeophytesLongbowOfDisciplineName, "Neophyte's Longbow of Discipline" },
            { LocalizationIds.Mod.NeophytesLongbowOfDisciplineDescription, "This +1 composite longbow deals an additional 1d6 force damage to chaotic targets." },
            { LocalizationIds.Mod.BillyPilgrimageRecordName, "Scorched Pilgrimage Record" },
            { LocalizationIds.Mod.BillyPilgrimageRecordDescription, "A brittle page from a Kenabres custody ledger, its edges blackened and its seal scraped away.\n\nThe legible lines mention a foreign Iroran novice archer, a Jalmeray cadence, and effects forwarded under \"H.\" to the old tunnels. The final entry is worse: \"Body absent from second count. Do not correct the numbers. Do not question the Path.\"" },
            { LocalizationIds.Mod.ArchersTunicName, "Irori Neophyte's Armor" },
            { LocalizationIds.Mod.ArchersTunicDescription, "This +1 breastplate grants its wearer a +1 bonus on attack and damage rolls with bows." },
            { LocalizationIds.Mod.ScythePlus1Name, "+1 Scythe" },
            { LocalizationIds.Mod.ScythePlus1Description, "This finely balanced scythe carries a simple +1 enhancement bonus." },
            { LocalizationIds.Mod.ShortswordPlus1Name, "+1 Shortsword" },
            { LocalizationIds.Mod.ShortswordPlus1Description, "This finely balanced shortsword carries a simple +1 enhancement bonus." },
            { LocalizationIds.Mod.BillyName, "Billy" },
            { LocalizationIds.Mod.BillyGreeting, "Oh, you almost scared me to death. Wait, too late for that! Anyways, I thought you were another one of those crazy cultists." },
            { LocalizationIds.Mod.BillyJoinCue, "All right. I'll come with you." },
            { LocalizationIds.Mod.BillyJoinAnswer, "Come with us." },
            { LocalizationIds.Mod.BillyLeaveAnswer, "Stay here for now." },
            { LocalizationIds.Mod.BillyWhatAreYouAnswer, "What are you?" },
            { LocalizationIds.Mod.BillyWhatAreYouCue, "Technically? A violation of several natural laws. Practically? Still me. Still thinking. Still shooting straighter than most of the living. Look, I get it. I'm not supposed to be up and walking around. I've filed that complaint myself. But until the universe processes the paperwork, I've got things to do." },
            { LocalizationIds.Mod.BillyWhyHereAnswer, "Why are you here?" },
            { LocalizationIds.Mod.BillyWhyHereCue, "Same reason as you, I'm guessing. The world's ending, demons are everywhere, and nobody else is doing the job right. I follow Irori. Self-perfection. Discipline. Mastery. Turns out death is just an unexpected training condition. So here I am. Improving. Adapting. Trying not to fall apart, literally or philosophically." },
            { LocalizationIds.Mod.BillyDangerousAnswer, "Are you dangerous?" },
            { LocalizationIds.Mod.BillyDangerousCue, "To enemies? Absolutely. To you? Not unless you start chanting in Abyssal or sprout extra limbs. I've got standards." },
            { LocalizationIds.Mod.BillyPlanAnswer, "What do you plan to do now?" },
            { LocalizationIds.Mod.BillyPlanCue, "Keep moving. Keep improving. Keep putting arrows into things that deserve it. And maybe, eventually, figure out whether this is something to fix or something to master." },
            { LocalizationIds.Mod.BillyHubGreeting, "Need something?" },
            { LocalizationIds.Mod.BillyBowQuestStartCue, "That's my bow! How did this crazy bitch get it? I left it at the temple near Jalmeray... no. I was holding it. Sun-warmed stone, salt incense, the training hall bell, then nothing until I woke up in a crypt with dirt in my mouth and prayer beads in my ribs." },
            { LocalizationIds.Mod.BillyBowQuestTempleAnswer, "Slow down. What is the last thing you remember from Jalmeray?" },
            { LocalizationIds.Mod.BillyBowQuestTempleCue, "Evening practice. Three breaths, one shot. Draw, hold, release. Again. Again. My fingers were split raw, and I was proud of it. Master Kalas said discipline is what remains when terror arrives. Then cold candle-smoke, a hand on my shoulder, and my bow hitting the floor. Or maybe that was me." },
            { LocalizationIds.Mod.BillyBowQuestHosillaAnswer, "Hosilla having it means someone carried it across half the Inner Sea to Kenabres." },
            { LocalizationIds.Mod.BillyBowQuestHosillaCue, "That's the cheerful arithmetic, yes. A cultist chief didn't find Jalmeray temple property in a barrel of discount blasphemy. Someone took this from me, or from my body, and brought it under Kenabres. I very much want to know which version is worse." },
            { LocalizationIds.Mod.BillyBowQuestDisciplineAnswer, "The bow still punishes chaotic foes. Irori's discipline survived with you." },
            { LocalizationIds.Mod.BillyBowQuestDisciplineCue, "Comforting in the most upsetting possible way. If the bow remembers my vows better than I remember my death, maybe it can point us backward. Not literally, I assume. Though if it starts humming, everyone stay calm." },
            { LocalizationIds.Mod.BillyBowQuestEndAnswer, "We'll find out what happened to you." },
            { LocalizationIds.Mod.BillyBowQuestEndCue, "Good. Because if my last living day ended near Jalmeray, then my first undead step under Kenabres was not an accident. And if someone dragged me across the continent to become this, I intend to discuss personal growth with them at arrowpoint." },
            { LocalizationIds.Mod.BillyAct1JalmerayAnswer, "Someone at Defender's Heart recognized one of your training phrases." },
            { LocalizationIds.Mod.BillyAct1JalmerayCue, "Three breaths, one shot? That's not a Kenabres drill. That's from the Jalmeray temples, or close enough that my bones remember the rhythm. If someone here knows it, then my path to this city left tracks. Good. Tracks can be followed." },
            { LocalizationIds.Mod.BillyAct1JalmerayContinueAnswer, "Continue." },
            { LocalizationIds.Mod.BillyAct1RecordAnswer, "We found a scorched record about a Jalmeray archer." },
            { LocalizationIds.Mod.BillyAct1RecordCue, "That is me, unless Kenabres imported a second dead Iroran with excellent posture and terrible luck. \"Body absent from second count\" is a tidy way to say someone misplaced my corpse on purpose. Hosilla had my bow, but this says she was only one hand on the rope." },
            { LocalizationIds.Mod.BillyAct1TunicAnswer, "This breastplate was hidden in the cult cache." },
            { LocalizationIds.Mod.BillyAct1TunicCue, "Temple work, but altered. See the shoulder? Reinforced for a bow arm. See the side plates? Cut so a stiff corpse would not fight them when it moved. Practical, monstrous, and annoyingly competent. Keep it. If someone made a uniform for what they expected me to become, I would rather see it used against them." },
            { LocalizationIds.Mod.BillyIroriDisciplineName, "Irori's Discipline" },
            { LocalizationIds.Mod.BillyIroriDisciplineDescription, "Billy's devotion to Irori turns discipline into protection. While unarmored and unencumbered, he adds his Wisdom bonus to AC. This bonus increases by +1 at 4th level and every 4 levels thereafter." },
            { LocalizationIds.Mod.BillyWayOfTheBowName, "Billy's Way of the Bow" },
            { LocalizationIds.Mod.BillyWayOfTheBowDescription, "Billy expresses Irori's teachings through exacting longbow practice. He gains Weapon Focus with longbows. At 6th level, this training also grants Weapon Specialization with longbows." },
            { LocalizationIds.Mod.BillyStoryTitle, "Ashes Unburied" },
            { LocalizationIds.Mod.BillyStoryDescription, "The undead priest has wandered the depths of the Shield Maze for years, sustaining himself through discipline, prayer, and grim determination. Though death claimed his flesh long ago, his faith in Irori remains unbroken, and he treats his cursed existence as yet another trial to master through patience and self-control. Endless battles against cultists and demons have left him sharp-tongued and eccentric, but not cruel. After so many years surrounded by madness, corruption, and the restless dead, the Commander's party are the first sane souls he has encountered in what feels like a lifetime, and he clings to their company more tightly than he would ever willingly admit." },
            { LocalizationIds.Mod.BillyConditionQuestTitle, "Billy's Condition" },
            { LocalizationIds.Mod.BillyConditionQuestDescription, "Billy recognized the longbow taken from Hosilla. It may be a surviving thread from his last living day near Jalmeray, and following it could reveal who brought an Irori novice beneath Kenabres and turned him into an undead archer." },
            { LocalizationIds.Mod.BillyConditionQuestCompletion, "Billy has learned more about the circumstances of his death and undeath." },
            { LocalizationIds.Mod.BillyConditionInvestigateTitle, "Investigate Billy's death" },
            { LocalizationIds.Mod.BillyConditionInvestigateDescription, "Billy's bow was found in Hosilla's possession, far from the Jalmeray-area temple where he remembers training. Find out how it reached the cultists, and what happened to Billy before he woke in the Shield Maze." },
            { LocalizationIds.Mod.BillyConditionAct1JalmerayLeadTitle, "Ask about the Jalmeray drill" },
            { LocalizationIds.Mod.BillyConditionAct1JalmerayLeadDescription, "At Defender's Heart, someone recognized one of Billy's training phrases as an Iroran archery drill from the Jalmeray area. Look for anyone in Kenabres who might know why a novice from so far away was brought beneath the city." },
            { LocalizationIds.Mod.BillyConditionTransferRecordTitle, "Trace the second transfer" },
            { LocalizationIds.Mod.BillyConditionTransferRecordDescription, "A scorched record in Market Square says a foreign Iroran novice matching Billy was moved through Kenabres under Hosilla's people before his body vanished from the count. Search for the cult cache or handler who received the transfer." },
            { LocalizationIds.Mod.BillyConditionAct1TrailColdTitle, "Wait for another lead" },
            { LocalizationIds.Mod.BillyConditionAct1TrailColdDescription, "The cult cache held a tunic prepared for an archer and notes implying Billy was preserved to test whether discipline, memory, and obedience survived undeath. The trail ends in Kenabres for now, but someone beyond Hosilla planned the transfer." },
            { LocalizationIds.Mod.EvokerName, "Evoker" },
            { LocalizationIds.Mod.EvokerDescription, "Evokers are storm-hearted spellcasters who do not merely cast destructive magic - they conduct it. Their spell shaping turns raw force, flame, frost, lightning, and acid into precise instruments, driving Evocation spells beyond ordinary damage limits while bending their fury around allies." },
            { LocalizationIds.Mod.EvokerBonusFeatName, "Evoker Bonus Feat" },
            { LocalizationIds.Mod.EvokerBonusFeatDescription, "At 2nd, 6th, 10th, 14th, and 18th level, an Evoker gains a bonus feat in addition to those gained from normal advancement. This bonus feat must be selected from combat feats, metamagic feats, or Spell Focus." },
            { LocalizationIds.Mod.EvokerProficienciesName, "Evoker Proficiencies" },
            { LocalizationIds.Mod.EvokerProficienciesDescription, "Evokers are proficient with all simple weapons." },
            { LocalizationIds.Mod.ElementalConversionName, "Elemental Conversion" },
            { LocalizationIds.Mod.ElementalConversionDescription, "An Evoker's elemental arcana can be invoked as a toggle, retuning destructive spells to the element they command. Flame, frost, thunder, and acid become choices of expression rather than limits of the spell." },
            { LocalizationIds.Mod.EvocationUnleashedName, "Evocation Unleashed" },
            { LocalizationIds.Mod.EvocationUnleashedDescription, "An Evoker shapes destruction with absolute control. Their Evocation spells add the Evoker's Charisma bonus to damage, and Evocation spells cast from the Evoker spellbook shape to bend the blast around allies caught in the spell's fury." },
            { LocalizationIds.Mod.EvokerFamiliarName, "Evoker's Familiar" },
            { LocalizationIds.Mod.EvokerFamiliarDescription, "An Evoker forms a bond with a familiar companion that fights at their side and grows in power with their Evoker levels." },
            { LocalizationIds.Mod.ArcanistEvokerName, "Arcwright" },
            { LocalizationIds.Mod.ArcanistEvokerDescription, "An Arcwright fixes their bloodline to raw arcane force, replacing the normal Evoker bloodline choice with the Arcwright progression. At 4th level and again at 9th, 13th, and 17th levels, they may add one spell from the wizard spell list to their Evoker spellbook, even if that spell is not on the Evoker spell list." },
            { LocalizationIds.Mod.ArcanistEvokerBonusFeatName, "Arcwright Bonus Feat" },
            { LocalizationIds.Mod.ArcanistEvokerBonusFeatDescription, "At 6th, 12th, and 18th level, an Arcwright gains a bonus feat selected from the Evoker bloodline feat list." },
            { LocalizationIds.Mod.ArcanistEvokerNewArcanaName, "New Arcana" },
            { LocalizationIds.Mod.ArcanistEvokerNewArcanaDescription, "At 4th level and again at 9th, 13th, and 17th levels, an Arcwright may add one spell from the wizard spell list to their Evoker spellbook, even if that spell is not on the Evoker spell list." },
            { LocalizationIds.Mod.ShadowbornName, "Shadowborn" },
            { LocalizationIds.Mod.ShadowbornDescription, "A Shadowborn follows a dark reflection of the Evoker's Pyromancer bloodline, replacing the usual bloodline choice with negative-energy powers shaped from living shadow." },
            { LocalizationIds.Mod.DraconicEvokerName, "Draconic Evoker" },
            { LocalizationIds.Mod.DraconicEvokerDescription, "A Draconic Evoker channels destructive magic through the raw elemental might of dragonkind, replacing the usual Evoker bloodlines with draconic bloodlines. Draconic Evokers are melee- or midrange-focused casters with 3/4 base attack bonus progression and a stronger martial foundation. They gain light armor proficiency and do not suffer arcane spell failure from light armor when casting Evoker spells. At 4th level, this expands to medium armor, and at 9th level, it expands to heavy armor." },
            { LocalizationIds.Mod.DraconicEvokerBloodlineName, "Draconic Evoker Bloodline" },
            { LocalizationIds.Mod.DraconicEvokerBloodlineDescription, "Select a draconic bloodline. Draconic Evokers can choose only dragon bloodlines." },
            { LocalizationIds.Mod.DraconicEvokerBreathWeaponName, "Breath Weapon" },
            { LocalizationIds.Mod.DraconicEvokerBreathWeaponDescription, "A Draconic Evoker exhales raw dragon power with far greater force than an ordinary bloodline bearer. At 9th level, this breath weapon deals 1d8 damage per Evoker level, plus 1 damage per die. At 17th level, it increases to 1d10 damage per Evoker level, plus 2 damage per die. At 20th level, it increases to 1d12 damage per Evoker level, plus 3 damage per die. A successful Reflex save halves the damage." },
            { LocalizationIds.Mod.DraconicEvokerLightArmorProficiencyName, "Light Armor Proficiency" },
            { LocalizationIds.Mod.DraconicEvokerLightArmorProficiencyDescription, "A Draconic Evoker is proficient with light armor and does not suffer arcane spell failure from light armor when casting Evoker spells." },
            { LocalizationIds.Mod.DraconicEvokerMediumArmorProficiencyName, "Medium Armor Proficiency" },
            { LocalizationIds.Mod.DraconicEvokerMediumArmorProficiencyDescription, "A Draconic Evoker is proficient with medium armor and does not suffer arcane spell failure from light or medium armor when casting Evoker spells." },
            { LocalizationIds.Mod.DraconicEvokerHeavyArmorProficiencyName, "Heavy Armor Proficiency" },
            { LocalizationIds.Mod.DraconicEvokerHeavyArmorProficiencyDescription, "A Draconic Evoker is proficient with heavy armor and does not suffer arcane spell failure from light, medium, or heavy armor when casting Evoker spells." },
            { LocalizationIds.Mod.ShadowbornBloodlineName, "Shadowborn" },
            { LocalizationIds.Mod.ShadowbornBloodlineDescription, "Your bloodline burns with lightless power, shaping the Evoker's destructive gifts into negative energy." },
            { LocalizationIds.Mod.ShadowbornArcanaName, "Umbral Arcana" },
            { LocalizationIds.Mod.ShadowbornArcanaDescription, "Your damaging spells can be infused with living shadow, changing elemental damage into negative energy." },
            { LocalizationIds.Mod.ShadowbornBurningHandsName, "Shadow Hands" },
            { LocalizationIds.Mod.ShadowbornBurningHandsDescription, "A cone of grasping shadow deals 1d4 negative energy damage per caster level." },
            { LocalizationIds.Mod.ShadowbornScorchingRayName, "Shadow Ray" },
            { LocalizationIds.Mod.ShadowbornScorchingRayDescription, "A ray of concentrated shadow deals 4d6 negative energy damage with a ranged touch attack. For every 4 caster levels beyond 3rd, you gain one additional ray." },
            { LocalizationIds.Mod.ShadowbornUmbralRayName, "Umbral Ray" },
            { LocalizationIds.Mod.ShadowbornUmbralRayDescription, "You can unleash a ray of living shadow as a standard action, targeting any foe within 30 feet as a ranged touch attack. This ray deals 1d6 negative energy damage at 1st level, plus 1d6 for every two Evoker levels beyond 1st. You can use this ability a number of times per day equal to your Evoker level plus your Charisma modifier." },
            { LocalizationIds.Mod.ShadowbornUmbralBlastName, "Umbral Blast" },
            { LocalizationIds.Mod.ShadowbornUmbralBlastDescription, "At 9th level, you can release a 20-foot burst of living shadow. This blast deals 1d6 negative energy damage per Evoker level. A successful Reflex save halves the damage." },
            { LocalizationIds.Mod.ShadowbornResistanceName, "Umbral Resistance" },
            { LocalizationIds.Mod.ShadowbornResistanceDescription, "At 3rd level, your shadowed blood grants negative energy resistance 10. At 9th level, this resistance increases to 20." },
            { LocalizationIds.Mod.ShadowbornElementalBodyName, "Umbral Body" },
            { LocalizationIds.Mod.ShadowbornElementalBodyDescription, "At 14th level, your body becomes a vessel for lightless power. Negative energy heals you instead of harming you. If you are undead, negative energy heals you for twice as much." },
            { LocalizationIds.Mod.ShadowbornScalingName, "Shadowborn - Umbral Potency" },
            { LocalizationIds.Mod.ShadowbornScalingDescription, "Your shadowed spells drink deeper from the dark. Evocation spells cast from your Evoker spellbook that deal negative energy damage gain +1 damage per die per rank. While Umbral Arcana is active, this bonus also applies to elemental energy damage converted into negative energy. Ranks increase at levels 1, 5, 9, 13, and 17." },
            { LocalizationIds.Mod.ShadowbornBonusFeatName, "Evoker Bonus Feat" },
            { LocalizationIds.Mod.ShadowbornBonusFeatDescription, "At 1st, 6th, 10th, 16th, and 20th level, an Evoker gains a bonus feat in addition to those gained from normal advancement. This bonus feat must be selected from combat feats, metamagic feats, or Spell Focus." },
            { LocalizationIds.Mod.ShadowbornLivingGhostName, "Living Ghost" },
            { LocalizationIds.Mod.ShadowbornLivingGhostDescription, "At 20th level, a Shadowborn can become incorporeal as a free-action toggle." },
            { LocalizationIds.Mod.ShadowbornShadowMasteryName, "Shadow Mastery" },
            { LocalizationIds.Mod.ShadowbornShadowMasteryDescription, "At 6th level, a Shadowborn's negative energy damage is so pure that it ignores creatures' resistance to negative energy." },
            { LocalizationIds.Mod.NecromancerName, "Necromancer" },
            { LocalizationIds.Mod.NecromancerDescription, "A spontaneous arcane caster who rejects traditional bloodlines and draws power from death itself." },
            { LocalizationIds.Mod.SepulchritName, "Sepulchrit" },
            { LocalizationIds.Mod.SepulchritDescription, "A Sepulchrit approaches necromancy through study, formulae, and the patient cataloging of death. This archetype prepares spells from a spellbook and has access to both the necromancer spell list and the full wizard spell list. It uses Intelligence instead of Charisma for necromancer spellcasting." },
            { LocalizationIds.Mod.GravebladeName, "Graveblade" },
            { LocalizationIds.Mod.GravebladeDescription, "A Graveblade drags necromancy onto the front line, feeding on the nearness of death to sharpen steel, harden sinew, and strike with the sure, practiced accuracy of a dedicated warrior. Graveblades use full base attack bonus progression." },
            { LocalizationIds.Mod.GravebladeProficienciesName, "Graveblade Proficiencies" },
            { LocalizationIds.Mod.GravebladeProficienciesDescription, "Graveblades are proficient with light armor, medium armor, heavy armor, all simple weapons, and all martial weapons." },
            { LocalizationIds.Mod.GravebladeBonusFeatName, "Graveblade Bonus Feat" },
            { LocalizationIds.Mod.GravebladeBonusFeatDescription, "At 2nd, 6th, 10th, 14th, and 18th level, a graveblade can draw from the necromancer bonus feat list or from the martial techniques normally reserved for fighters." },
            { LocalizationIds.Mod.GravebladeFighterTrainingName, "Graveblade Training" },
            { LocalizationIds.Mod.GravebladeFighterTrainingDescription, "A graveblade's necromantic combat drills count their graveblade levels as fighter levels when qualifying for feats chosen through Graveblade Bonus Feat. This training also allows a graveblade to cast necromancy spells in light, medium, and heavy armor without arcane spell failure." },
            { LocalizationIds.Mod.DeathstalkerName, "Deathstalker" },
            { LocalizationIds.Mod.DeathstalkerDescription, "A Deathstalker hunts silently, striking from the shadows and vanishing before the grave closes. Light on their feet and lighter in armor, they blend the silence of death with an assassin's finesse, dropping foes with well-placed sneak attacks and, at the height of their power, a single deathblow no ward can turn aside. Deathstalkers use full base attack bonus progression and cast necromancy spells with the speed of a seasoned battle-caster." },
            { LocalizationIds.Mod.DeathstalkerProficienciesName, "Deathstalker Proficiencies" },
            { LocalizationIds.Mod.DeathstalkerProficienciesDescription, "Deathstalkers are proficient with light armor, all simple weapons, and all martial weapons, and gain Lightning Reflexes and Weapon Finesse as bonus feats. Mobility, Perception, Stealth, and Thievery are class skills for a deathstalker." },
            { LocalizationIds.Mod.DeathstalkerBonusFeatName, "Deathstalker Bonus Feat" },
            { LocalizationIds.Mod.DeathstalkerBonusFeatDescription, "At 2nd, 6th, 10th, 14th, and 18th level, a deathstalker can draw from the necromancer bonus feat list, the martial techniques normally reserved for fighters, or the larcenous training of rogue talents." },
            { LocalizationIds.Mod.DeathstalkerFighterTrainingName, "Deathstalker Training" },
            { LocalizationIds.Mod.DeathstalkerFighterTrainingDescription, "A deathstalker is the dark assassin of necromancy, utilizing both fighter and rogue skills. Their deathstalker levels count as both fighter levels and rogue levels when qualifying for feats chosen through Deathstalker Bonus Feat, and their martial drills let them cast necromancy spells in light armor without arcane spell failure." },
            { LocalizationIds.Mod.DeathstalkerTrapfindingName, "Trapfinding" },
            { LocalizationIds.Mod.DeathstalkerTrapfindingDescription, "A deathstalker adds half their level on Perception checks." },
            { LocalizationIds.Mod.DeathstalkerMasterStrikeName, "Master Strike" },
            { LocalizationIds.Mod.DeathstalkerMasterStrikeDescription, "At 20th level, a deathstalker's sneak attack can end a fight in one blow. Once per target per day, if a creature struck by the deathstalker's sneak attack fails a Fortitude save (DC 10 + half the deathstalker's level + their Dexterity modifier), it dies instantly." },
            { LocalizationIds.Mod.DeathstalkerFinesseTrainingName, "Finesse Training" },
            { LocalizationIds.Mod.DeathstalkerFinesseTrainingDescription, "A deathstalker can use their Dexterity modifier instead of Strength for damage rolls with a chosen weapon. At 2nd level, and again at 5th, 8th, and 13th level, they choose another weapon to gain this benefit with." },
            { LocalizationIds.Mod.DeathstalkerWraithstep1Name, "Wraithstep" },
            { LocalizationIds.Mod.DeathstalkerWraithstep1Description, "At 3rd level, a deathstalker moves with the fleeting grace of the dead, increasing their base speed by 10 feet." },
            { LocalizationIds.Mod.DeathstalkerWraithstep2Name, "Shadow's Grace" },
            { LocalizationIds.Mod.DeathstalkerWraithstep2Description, "At 7th level, a deathstalker's base speed increases by another 10 feet, and they are permanently immune to the effects of difficult terrain." },
            { LocalizationIds.Mod.DeathstalkerWraithstep3Name, "Necrostride" },
            { LocalizationIds.Mod.DeathstalkerWraithstep3Description, "At 11th level, a deathstalker's base speed increases by another 10 feet, and they no longer provoke attacks of opportunity for moving." },
            { LocalizationIds.Mod.DeathstalkerWraithstep4Name, "True Wraithstep" },
            { LocalizationIds.Mod.DeathstalkerWraithstep4Description, "At 15th level, a deathstalker's base speed increases by another 10 feet, and they can cast dimension door on themselves as a spell-like ability at will." },
            { LocalizationIds.Mod.DeathstalkerDimensionDoorName, "Dimension Door" },
            { LocalizationIds.Mod.DeathstalkerDimensionDoorDescription, "You instantly transfer yourself from your current location to any other spot within range. You may also bring with you all friendly creatures within a 10-foot radius around you." },
            { LocalizationIds.Mod.GravebladeArmorMasteryName, "Graveforged Armor" },
            { LocalizationIds.Mod.GravebladeArmorMasteryDescription, "At 19th level, a graveblade's armor becomes a reliquary of battle-scarred bone and cold iron. While wearing armor, the graveblade gains DR 10/-." },
            { LocalizationIds.Mod.NecromancerStygianPrecisionName, "Stygian Precision" },
            { LocalizationIds.Mod.NecromancerStygianPrecisionDescription, "At 4th, 8th, 12th, and 16th level, a necromancer's critical hit range with scythes increases by 1." },
            { LocalizationIds.Mod.NecromancerReapersJudgementName, "Reaper's Judgement" },
            { LocalizationIds.Mod.NecromancerReapersJudgementDescription, "At 20th level, a necromancer's critical hit range with scythes increases by 1. In addition, while wielding a scythe, the necromancer automatically confirms critical hits." },
            { LocalizationIds.Mod.GravebladeReapingEdgeName, "The Reaping Edge" },
            { LocalizationIds.Mod.GravebladeReapingEdgeDescription, "As a swift action, you can turn your weapon into a conduit for the Weight of the Grave for your next strike. You can use this ability a number of times per day equal to your Necromancer level plus your Charisma modifier, and expended uses are restored when you rest.\n\nAt 1st level, your weapon deals an extra 1d6 negative energy damage, plus another 1d6 at every odd Graveblade level thereafter, and is treated as magical for overcoming damage reduction. The extra damage is doubled while wielding a scythe.\n\nAt 5th level, enemies hit by The Reaping Edge take a -2 penalty to AC for 1 round.\n\nAt 10th level, your weapon ignores the target's damage reduction entirely.\n\nAt 15th level, critical hits fatigue the target for 1 minute with no save. If the target is already fatigued, it becomes exhausted instead.\n\nAt 20th level, if you kill an enemy with a weapon attack while The Reaping Edge is active, bone shards deal your weapon's base damage to adjacent enemies." },
            { LocalizationIds.Mod.GravebladeReapingEdgeBaseName, "Reaping Edge" },
            { LocalizationIds.Mod.GravebladeReapingEdgeBaseDescription, "At 1st level, you can activate The Reaping Edge as a swift action a number of times per day equal to your Necromancer level plus your Charisma modifier. Expended uses are restored when you rest. Your next melee strike deals an extra 1d6 negative energy damage, plus another 1d6 at every odd Graveblade level thereafter, and is treated as magical for overcoming damage reduction. The extra damage is doubled while wielding a scythe." },
            { LocalizationIds.Mod.GravebladeReapingEdgeBrittleBoneFeatureName, "Brittle Bone" },
            { LocalizationIds.Mod.GravebladeReapingEdgeBrittleBoneFeatureDescription, "At 5th level, enemies hit by The Reaping Edge take a -2 penalty to AC for 1 round." },
            { LocalizationIds.Mod.GravebladeReapingEdgeEvilName, "Profane Edge" },
            { LocalizationIds.Mod.GravebladeReapingEdgeEvilDescription, "At 10th level, the grave itself profanes your strikes. Attacks empowered by The Reaping Edge ignore the target's damage reduction entirely." },
            { LocalizationIds.Mod.GravebladeReapingEdgeLingeringRotFeatureName, "Lingering Rot" },
            { LocalizationIds.Mod.GravebladeReapingEdgeLingeringRotFeatureDescription, "At 15th level, critical hits with The Reaping Edge fatigue the target for 1 minute with no save. If the target is already fatigued, it becomes exhausted instead." },
            { LocalizationIds.Mod.GravebladeReapingEdgeBoneShardsName, "Bone Shards" },
            { LocalizationIds.Mod.GravebladeReapingEdgeBoneShardsDescription, "At 20th level, if you kill an enemy with a weapon attack while The Reaping Edge is active, bone shards deal your weapon's base damage to adjacent enemies." },
            { LocalizationIds.Mod.GravebladeReapingEdgeBuffName, "The Reaping Edge" },
            { LocalizationIds.Mod.GravebladeReapingEdgeBuffDescription, "Your weapon carries the Weight of the Grave." },
            { LocalizationIds.Mod.GravebladeReapingEdgeBrittleBoneName, "Brittle Bone" },
            { LocalizationIds.Mod.GravebladeReapingEdgeBrittleBoneDescription, "Armor and flesh turn brittle, causing a -2 penalty to AC." },
            { LocalizationIds.Mod.GravebladeReapingEdgeFatigueName, "Lingering Rot" },
            { LocalizationIds.Mod.GravebladeReapingEdgeFatigueDescription, "The target is fatigued by necrotic rot." },
            { LocalizationIds.Mod.GravebladeReapingEdgeExhaustionName, "Lingering Rot" },
            { LocalizationIds.Mod.GravebladeReapingEdgeExhaustionDescription, "The target is exhausted by necrotic rot." },
            { LocalizationIds.Mod.NecromancerProficienciesName, "Necromancer Proficiencies" },
            { LocalizationIds.Mod.NecromancerProficienciesDescription, "Necromancers are proficient with all simple weapons and the scythe." },
            { LocalizationIds.Mod.NecromancerBonusFeatName, "Necromancer Bonus Feat" },
            { LocalizationIds.Mod.NecromancerBonusFeatDescription, "At 2nd, 6th, 10th, 14th, and 18th level, a necromancer gains a bonus feat in addition to those gained from normal advancement. These bonus feats must be selected from those listed as combat feats, metamagic feats, or Spell Focus." },
            { LocalizationIds.Mod.EvokerBloodlineName, "Evoker Bloodline" },
            { LocalizationIds.Mod.EvokerBloodlineDescription, "Select an evoker bloodline. Evokers channel their power through a narrow set of destructive traditions." },
            { LocalizationIds.Mod.NecromancerBloodlineName, "Necromancer" },
            { LocalizationIds.Mod.NecromancerBloodlineDescription, "Necromancers draw power from death and undeath." },
            { LocalizationIds.Mod.NecromancerBloodlineArcanaName, "Master of Death" },
            { LocalizationIds.Mod.NecromancerBloodlineArcanaDescription, "Your natural affinity to death grants a damage bonus per die for necromancy spells cast from your Necromancer spellbook, starting at +1 and increasing by 1 every 4 Necromancer levels, to a maximum of +6 at 20th level. At 4th level, these spells bypass 5 points of resistance to unholy and negative energy. This increases to 10 points at 8th level. At 12th level, they ignore all resistance to unholy and negative energy." },
            { LocalizationIds.Mod.NecromancerBloodlinePower1Name, "Withering Ray" },
            { LocalizationIds.Mod.NecromancerBloodlinePower1Description, "At 1st level, you can unleash a withering ray as a standard action, targeting any foe within 30 feet as a ranged touch attack. This ray deals 1d6 unholy damage at 1st level, plus 1d6 for every two Necromancer levels beyond 1st, plus your spellcasting ability bonus. You can use this ability a number of times per day equal to your Necromancer level plus your spellcasting ability modifier." },
            { LocalizationIds.Mod.NecromancerBloodlinePower3Name, "Death's Gift" },
            { LocalizationIds.Mod.NecromancerBloodlinePower3Description, "At 3rd level, you gain DR 5/magic and cold resistance 5. These bonuses improve to 10 at 9th level and 20 at 15th level." },
            { LocalizationIds.Mod.NecromancerBloodlinePower9Name, "Grasp of the Dead" },
            { LocalizationIds.Mod.NecromancerBloodlinePower9Description, "At 9th level, you can cause a swarm of skeletal arms to burst from the ground in a 20-foot burst. This deals 1d6 points of slashing damage per caster level." },
            { LocalizationIds.Mod.NecromancerBloodlinePower15Name, "Incorporeal Form" },
            { LocalizationIds.Mod.NecromancerBloodlinePower15Description, "At 15th level, you can become incorporeal for a number of rounds equal to your caster level." },
            { LocalizationIds.Mod.NecromancerBloodlinePower20Name, "One of Us" },
            { LocalizationIds.Mod.NecromancerBloodlinePower20Description, "At 20th level, you become one of the undead. You gain immunity to cold, nonlethal damage, paralysis, and sleep." },
            { LocalizationIds.Mod.NecromancerBoneArmorName, "Bone Armor" },
            { LocalizationIds.Mod.NecromancerBoneArmorDescription, "A silent ward of bone encases you, granting a +1 natural armor bonus to AC. This bonus increases by +1 at 5th level and every four levels thereafter, to a maximum of +5 at 17th level." },
            { LocalizationIds.Mod.NecromancerMasterOfDeathClassCardDescription, "Necromancers turn the cold grammar of death into a weapon. Their necromancy spells draw extra power from every damage die and increasingly penetrate resistance to unholy and negative energy." },
            { LocalizationIds.Mod.NecromancerWitheringRayClassCardDescription, "A Necromancer can fire a ray of wasting death at close range, dealing unholy damage that grows with the Necromancer's level and gains the caster's spellcasting ability bonus." },
            { LocalizationIds.Mod.NecromancerBoneArmorClassCardDescription, "A Necromancer is never truly unguarded. Pale plates, splinters, and spectral ribs gather around them as they grow in power, forming a grim ward that hardens their defenses without slowing their spellcasting." },
            { LocalizationIds.Mod.EvokerArcaneName, "Arcwright" },
            { LocalizationIds.Mod.EvokerArcaneDescription, "Your blood hums with raw arcane resonance, shaping pure magical force into devastating expressions of power." },
            { LocalizationIds.Mod.EvokerForceArcanaName, "Bloodline Arcana - Force" },
            { LocalizationIds.Mod.EvokerForceArcanaDescription, "As a toggle, your arcane bloodline retunes elemental spell damage into pure force while the arcana is active." },
            { LocalizationIds.Mod.EvokerForceRayName, "Force Beam" },
            { LocalizationIds.Mod.EvokerForceRayDescription, "You can unleash a force beam as a standard action, targeting any foe within 30 feet as a ranged touch attack. This beam deals 1d6 force damage at 1st level, plus 1d6 for every two Evoker levels beyond 1st. You can use this ability a number of times per day equal to your Evoker level plus your Charisma modifier." },
            { LocalizationIds.Mod.EvokerAirName, "Stormcaller" },
            { LocalizationIds.Mod.EvokerAirDescription, "Lightning dances at your fingertips and thunder rolls in your wake." },
            { LocalizationIds.Mod.EvokerEarthName, "Vitriomancer" },
            { LocalizationIds.Mod.EvokerEarthDescription, "Your power manifests as virulent acid and caustic corruption." },
            { LocalizationIds.Mod.EvokerFireName, "Pyromancer" },
            { LocalizationIds.Mod.EvokerFireDescription, "Flame is your birthright, and your magic burns with unrestrained intensity." },
            { LocalizationIds.Mod.EvokerWaterName, "Glacialist" },
            { LocalizationIds.Mod.EvokerWaterDescription, "Frost answers your call, locking enemies in killing cold." },
            { LocalizationIds.Mod.EvokerElementalRayName, "Elemental Ray" },
            { LocalizationIds.Mod.EvokerElementalRayDescription, "You can unleash an elemental ray as a standard action, targeting any foe within 30 feet as a ranged touch attack. This ray deals 1d6 energy damage at 1st level, plus 1d6 for every two Evoker levels beyond 1st. You can use this ability a number of times per day equal to your Evoker level plus your Charisma modifier." },
            { LocalizationIds.Mod.EvokerScalingArcaneName, "Arcwright - Arcane Supremacy" },
            { LocalizationIds.Mod.EvokerScalingArcaneDescription, "Your grasp of arcane structure makes your spells nearly unstoppable. You gain a +2 bonus to the Difficulty Class of Evocation spells cast from your Evoker spellbook per rank, and Force Beam gains +1 force damage per die per rank. Ranks increase at levels 1, 4, 8, 12, 16, and 20." },
            { LocalizationIds.Mod.EvokerScalingAirName, "Stormcaller - Tempest Surge" },
            { LocalizationIds.Mod.EvokerScalingAirDescription, "You channel the growing wrath of the storm. Evocation spells cast from your Evoker spellbook that deal electricity damage, and your Elemental Ray, gain +1 damage per die per rank. Ranks increase at levels 1, 5, 9, 13, 17, and 20; the 20th-level rank adds +2 damage per die instead of +1." },
            { LocalizationIds.Mod.EvokerScalingEarthName, "Vitriomancer - Corrosive Mastery" },
            { LocalizationIds.Mod.EvokerScalingEarthDescription, "Your corrosive magic intensifies with each milestone. Evocation spells cast from your Evoker spellbook that deal acid damage, and your Elemental Ray, gain +1 damage per die per rank. Ranks increase at levels 1, 5, 9, 13, 17, and 20; the 20th-level rank adds +2 damage per die instead of +1." },
            { LocalizationIds.Mod.EvokerScalingFireName, "Pyromancer - Infernal Potency" },
            { LocalizationIds.Mod.EvokerScalingFireDescription, "Your flames burn with escalating fury. Evocation spells cast from your Evoker spellbook that deal fire damage, and your Elemental Ray, gain +1 damage per die per rank. Ranks increase at levels 1, 5, 9, 13, 17, and 20; the 20th-level rank adds +2 damage per die instead of +1." },
            { LocalizationIds.Mod.EvokerScalingWaterName, "Glacialist - Glacial Dominion" },
            { LocalizationIds.Mod.EvokerScalingWaterDescription, "Your mastery of frost deepens with experience. Evocation spells cast from your Evoker spellbook that deal cold damage, and your Elemental Ray, gain +1 damage per die per rank. Ranks increase at levels 1, 5, 9, 13, 17, and 20; the 20th-level rank adds +2 damage per die instead of +1." },
            { LocalizationIds.Mod.LivingDarknessName1, "Creeping Darkness I" },
            { LocalizationIds.Mod.LivingDarknessDescription1, "At 7th level, you can call forth a 15-foot aura of creeping darkness centered on yourself, lasting 1 minute per caster level. You gain partial concealment (20% miss chance, stacks with other sources). Enemies within the aura take a -1 penalty to saving throws against your spells. You can use Creeping Darkness a number of times per day equal to your Evoker level + your Charisma modifier." },
            { LocalizationIds.Mod.LivingDarknessName2, "Creeping Darkness II" },
            { LocalizationIds.Mod.LivingDarknessDescription2, "At 11th level, your creeping darkness expands to a 20-foot aura centered on yourself, lasting 1 minute per caster level. You gain total concealment (50% miss chance, stacks with other sources). Enemies within the aura take a -2 penalty to saving throws against your spells and become Fatigued. Your negative energy spells bypass up to 5 points of the target's energy resistance. You can use Creeping Darkness a number of times per day equal to your Evoker level + your Charisma modifier." },
            { LocalizationIds.Mod.LivingDarknessName3, "Creeping Darkness III" },
            { LocalizationIds.Mod.LivingDarknessDescription3, "At 15th level, your creeping darkness expands to a 25-foot aura centered on yourself, lasting 1 minute per caster level. You gain total concealment (50% miss chance, stacks with other sources). Enemies within the aura take a -3 penalty to saving throws against your spells. On entering the aura, enemies must succeed at a Will saving throw or become Shaken. Your negative energy spells bypass up to 10 points of the target's energy resistance. You can use Creeping Darkness a number of times per day equal to your Evoker level + your Charisma modifier." },
            { LocalizationIds.Mod.LivingDarknessName4, "Creeping Darkness IV" },
            { LocalizationIds.Mod.LivingDarknessDescription4, "At 19th level, your creeping darkness expands to a 30-foot aura centered on yourself, lasting 1 minute per caster level. You gain total concealment (50% miss chance, stacks with other sources). Enemies within the aura take a -4 penalty to saving throws against your spells, must succeed at a Will saving throw or become Shaken, and take negative energy damage equal to your caster level each round. Your negative energy spells bypass up to 10 points of the target's energy resistance. You can use Creeping Darkness a number of times per day equal to your Evoker level + your Charisma modifier." },
            { LocalizationIds.Mod.LivingDarknessShakenName, "Wraithbound" },
            { LocalizationIds.Mod.LivingDarknessShakenDescription, "The creeping darkness has shaken you to your core." }
        };

        public static void Register(LocalizationTool localization)
        {
            foreach (var pair in Strings)
            {
                localization.Put(pair.Key, pair.Value);
            }
        }
    }
}
