using System.Collections.Generic;
using wotr_mod.Infrastructure;

namespace wotr_mod.Content.Localization
{
    internal static class ModText
    {
        private static readonly Dictionary<string, string> Strings = new Dictionary<string, string>
        {
            { LocalizationIds.Mod.BillyName, "Billy" },
            { LocalizationIds.Mod.BillyGreeting, "Oh, you almost scared me to death. Wait, too late for that! Anyways, I thought you were another one of those crazy cultists." },
            { LocalizationIds.Mod.BillyJoinCue, "All right. I'll come with you." },
            { LocalizationIds.Mod.BillyJoinAnswer, "Come with us." },
            { LocalizationIds.Mod.BillyLeaveAnswer, "Stay here for now." },
            { LocalizationIds.Mod.BillyWhatAreYouAnswer, "What are you?" },
            { LocalizationIds.Mod.BillyWhatAreYouCue, "Technically? A violation of several natural laws. Practically? Still me. Still thinking. Still shooting straighter than most of the living. Look, I get it. I'm not supposed to be up and walking around. I've filed that complaint myself. But until the universe processes the paperwork, I've got things to do." },
            { LocalizationIds.Mod.BillyWhyHereAnswer, "Why are you here?" },
            { LocalizationIds.Mod.BillyWhyHereCue, "Same reason as you, I'm guessing. The world's ending, demons are everywhere, and nobody else is doing the job right. I follow Irori. Self-perfection. Discipline. Mastery. Turns out death is just an unexpected training condition. So here I am. Improving. Adapting. Trying not to fall apart, literally or philosophically." },
            { LocalizationIds.Mod.BillyDangerousAnswer, "Are you dangerous?" },
            { LocalizationIds.Mod.BillyDangerousCue, "To enemies? Absolutely. To you? Not unless you start chanting in Abyssal or sprout extra limbs. I've got standards." },
            { LocalizationIds.Mod.BillyPlanAnswer, "What do you plan to do now?" },
            { LocalizationIds.Mod.BillyPlanCue, "Keep moving. Keep improving. Keep putting arrows into things that deserve it. And maybe, eventually, figure out whether this is something to fix or something to master." },
            { LocalizationIds.Mod.BillyIroriDisciplineName, "Irori's Discipline" },
            { LocalizationIds.Mod.BillyIroriDisciplineDescription, "Billy's devotion to Irori turns discipline into protection. While unarmored and unencumbered, he adds his Wisdom bonus to AC. This bonus increases by +1 at 4th level and every 4 levels thereafter." },
            { LocalizationIds.Mod.BillyWayOfTheBowName, "Billy's Way of the Bow" },
            { LocalizationIds.Mod.BillyWayOfTheBowDescription, "Billy expresses Irori's teachings through exacting longbow practice. He gains Weapon Focus with longbows. At 6th level, this training also grants Weapon Specialization with longbows." },
            { LocalizationIds.Mod.EvokerName, "Evoker" },
            { LocalizationIds.Mod.EvokerDescription, "An Evoker is a living conduit of raw, untamed power, channeling destructive arcane forces into devastating spells." },
            { LocalizationIds.Mod.ShadowbornName, "Shadowborn" },
            { LocalizationIds.Mod.ShadowbornDescription, "A Shadowborn follows a dark reflection of the Evoker's Pyromancer bloodline, replacing the usual bloodline choice with negative-energy powers shaped from living shadow." },
            { LocalizationIds.Mod.ShadowbornBloodlineName, "Shadowborn" },
            { LocalizationIds.Mod.ShadowbornBloodlineDescription, "Your bloodline burns with lightless power, shaping the Pyromancer's destructive gifts into negative energy." },
            { LocalizationIds.Mod.ShadowbornArcanaName, "Umbral Arcana" },
            { LocalizationIds.Mod.ShadowbornArcanaDescription, "Your damaging spells can be infused with living shadow, changing elemental damage into negative energy." },
            { LocalizationIds.Mod.ShadowbornBurningHandsName, "Shadow Hands" },
            { LocalizationIds.Mod.ShadowbornBurningHandsDescription, "A cone of grasping shadow deals 1d4 negative energy damage per caster level, to a maximum of 5d4 damage." },
            { LocalizationIds.Mod.ShadowbornScorchingRayName, "Shadow Ray" },
            { LocalizationIds.Mod.ShadowbornScorchingRayDescription, "A ray of concentrated shadow deals 4d6 negative energy damage with a ranged touch attack. For every 4 caster levels beyond 3rd, you gain one additional ray, to a maximum of three rays at caster level 11." },
            { LocalizationIds.Mod.ShadowbornUmbralRayName, "Umbral Ray" },
            { LocalizationIds.Mod.ShadowbornUmbralRayDescription, "You can unleash a ray of living shadow as a standard action, targeting any foe within 30 feet as a ranged touch attack. This ray deals 1d6 negative energy damage plus 1d6 for every two Evoker levels beyond 1st. You can use this ability a number of times per day equal to 3 + your Charisma modifier." },
            { LocalizationIds.Mod.ShadowbornUmbralBlastName, "Umbral Blast" },
            { LocalizationIds.Mod.ShadowbornUmbralBlastDescription, "At 9th level, you can release a 20-foot burst of living shadow. This blast deals 1d6 negative energy damage per Evoker level. A successful Reflex save halves the damage." },
            { LocalizationIds.Mod.ShadowbornResistanceName, "Umbral Resistance" },
            { LocalizationIds.Mod.ShadowbornResistanceDescription, "At 3rd level, your shadowed blood grants negative energy resistance 10. At 9th level, this resistance increases to 20." },
            { LocalizationIds.Mod.ShadowbornElementalBodyName, "Umbral Body" },
            { LocalizationIds.Mod.ShadowbornElementalBodyDescription, "At 20th level, your body becomes a vessel for lightless power. Negative energy heals you instead of harming you. If you are undead, negative energy heals you for twice as much." },
            { LocalizationIds.Mod.ShadowbornScalingName, "Shadowborn - Umbral Potency" },
            { LocalizationIds.Mod.ShadowbornScalingDescription, "Your shadowed spells drink deeper from the dark. Evocation spells cast from your Evoker spellbook that deal negative energy damage gain +1 damage per die per rank. While Umbral Arcana is active, this bonus also applies to elemental energy damage converted into negative energy. Ranks increase at levels 1, 5, 9, 13, and 17." },
            { LocalizationIds.Mod.NecromancerName, "Necromancer" },
            { LocalizationIds.Mod.NecromancerDescription, "A spontaneous arcane caster who rejects traditional bloodlines and draws power from death itself." },
            { LocalizationIds.Mod.SepulchritName, "Sepulchrit" },
            { LocalizationIds.Mod.SepulchritDescription, "A Sepulchrit approaches necromancy through study, formulae, and the patient cataloging of death. This archetype uses Intelligence instead of Charisma for necromancer spellcasting." },
            { LocalizationIds.Mod.GravebladeName, "Graveblade" },
            { LocalizationIds.Mod.GravebladeDescription, "A Graveblade drags necromancy onto the front line, feeding on the nearness of death to sharpen steel, harden sinew, and strike with the sure, practiced accuracy of a dedicated warrior. Graveblades use full base attack bonus progression." },
            { LocalizationIds.Mod.GravebladeProficienciesName, "Graveblade Proficiencies" },
            { LocalizationIds.Mod.GravebladeProficienciesDescription, "Graveblades are proficient with light armor, medium armor, heavy armor, and all martial weapons." },
            { LocalizationIds.Mod.GravebladeBonusFeatName, "Graveblade Bonus Feat" },
            { LocalizationIds.Mod.GravebladeBonusFeatDescription, "At 2nd, 6th, 10th, and 16th level, a graveblade can draw from the necromancer bonus feat list or from the martial techniques normally reserved for fighters." },
            { LocalizationIds.Mod.GravebladeFighterTrainingName, "Graveblade Training" },
            { LocalizationIds.Mod.GravebladeFighterTrainingDescription, "A graveblade's necromantic combat drills count their graveblade levels as fighter levels when qualifying for feats chosen through Graveblade Bonus Feat." },
            { LocalizationIds.Mod.GravebladeArmorMasteryName, "Graveforged Armor" },
            { LocalizationIds.Mod.GravebladeArmorMasteryDescription, "At 19th level, a graveblade's armor becomes a reliquary of battle-scarred bone and cold iron. While wearing armor, the graveblade gains DR 10/-." },
            { LocalizationIds.Mod.GravebladeReapingEdgeName, "The Reaping Edge" },
            { LocalizationIds.Mod.GravebladeReapingEdgeDescription, "As a swift action, you can turn your weapon into a conduit for the Weight of the Grave for 1 minute. You can use this ability a number of times per day equal to your Necromancer level x2 + your Charisma modifier.\n\nAt 1st level, your weapon deals an extra 1d6 negative energy damage and is treated as magical for overcoming damage reduction. This damage increases by 1d6 at every odd Necromancer level, and each mythic level counts as two levels for this damage scaling. The extra damage is doubled while wielding a scythe.\n\nAt 5th level, enemies hit by The Reaping Edge take a -2 penalty to AC for 1 round.\n\nAt 10th level, your weapon is treated as evil for overcoming damage reduction.\n\nAt 15th level, critical hits fatigue the target for 1 minute with no save. If the target is already fatigued, it becomes exhausted instead.\n\nAt 20th level, if you kill an enemy with a weapon attack while The Reaping Edge is active, bone shards deal your weapon's base damage to adjacent enemies." },
            { LocalizationIds.Mod.GravebladeReapingEdgeBuffName, "The Reaping Edge" },
            { LocalizationIds.Mod.GravebladeReapingEdgeBuffDescription, "Your weapon carries the Weight of the Grave." },
            { LocalizationIds.Mod.GravebladeReapingEdgeBrittleBoneName, "Brittle Bone" },
            { LocalizationIds.Mod.GravebladeReapingEdgeBrittleBoneDescription, "Armor and flesh turn brittle, causing a -2 penalty to AC." },
            { LocalizationIds.Mod.GravebladeReapingEdgeFatigueName, "Lingering Rot" },
            { LocalizationIds.Mod.GravebladeReapingEdgeFatigueDescription, "The target is fatigued by necrotic rot." },
            { LocalizationIds.Mod.GravebladeReapingEdgeExhaustionName, "Lingering Rot" },
            { LocalizationIds.Mod.GravebladeReapingEdgeExhaustionDescription, "The target is exhausted by necrotic rot." },
            { LocalizationIds.Mod.NecromancerProficienciesName, "Necromancer Proficiencies" },
            { LocalizationIds.Mod.NecromancerProficienciesDescription, "Necromancers are proficient with all simple weapons and the scythe." },
            { LocalizationIds.Mod.NecromancerBonusFeatName, "Necromancer Bonus Feat" },
            { LocalizationIds.Mod.NecromancerBonusFeatDescription, "At 6th, 10th, and 16th level, a necromancer gains a bonus feat in addition to those gained from normal advancement. These bonus feats must be selected from those listed as combat feats, metamagic feats, or Spell Focus." },
            { LocalizationIds.Mod.EvokerBloodlineName, "Evoker Bloodline" },
            { LocalizationIds.Mod.EvokerBloodlineDescription, "Select an evoker bloodline. Evokers channel their power through a narrow set of destructive traditions." },
            { LocalizationIds.Mod.NecromancerBloodlineName, "Necromancer" },
            { LocalizationIds.Mod.NecromancerBloodlineDescription, "Necromancers draw power from death and undeath." },
            { LocalizationIds.Mod.NecromancerBloodlineArcanaName, "Master of Death" },
            { LocalizationIds.Mod.NecromancerBloodlineArcanaDescription, "Your natural affinity to death grants a +1 damage bonus per die for necromancy spells cast from your Necromancer spellbook." },
            { LocalizationIds.Mod.NecromancerBloodlinePower1Name, "Withering Ray" },
            { LocalizationIds.Mod.NecromancerBloodlinePower1Description, "At 1st level, you can unleash a withering ray as a standard action, targeting any foe within 30 feet as a ranged touch attack. This ray deals 1d6 unholy damage, plus 1d6 for every two Necromancer levels beyond 1st. You can use this ability a number of times per day equal to 3 + your Charisma modifier." },
            { LocalizationIds.Mod.NecromancerBloodlinePower3Name, "Death's Gift" },
            { LocalizationIds.Mod.NecromancerBloodlinePower3Description, "At 3rd level, you gain DR 5/magic and cold resistance 5. These bonuses improve to 10 at 9th level and 20 at 15th level." },
            { LocalizationIds.Mod.NecromancerBloodlinePower9Name, "Grasp of the Dead" },
            { LocalizationIds.Mod.NecromancerBloodlinePower9Description, "At 9th level, you can cause a swarm of skeletal arms to burst from the ground in a 20-foot burst. This deals 1d6 points of slashing damage per caster level." },
            { LocalizationIds.Mod.NecromancerBloodlinePower15Name, "Incorporeal Form" },
            { LocalizationIds.Mod.NecromancerBloodlinePower15Description, "At 15th level, you can become incorporeal for a number of rounds equal to your caster level." },
            { LocalizationIds.Mod.NecromancerBloodlinePower20Name, "One of Us" },
            { LocalizationIds.Mod.NecromancerBloodlinePower20Description, "At 20th level, you become one of the undead. You gain immunity to cold, nonlethal damage, paralysis, and sleep." },
            { LocalizationIds.Mod.NecromancerBoneArmorName, "Bone Armor" },
            { LocalizationIds.Mod.NecromancerBoneArmorDescription, "A silent ward of bone encases you, granting a +1 natural armor bonus to AC. This bonus increases by +1 at 5th level and every four levels thereafter, to a maximum of +5 at 17th level." },
            { LocalizationIds.Mod.NecromancerMasterOfDeathClassCardDescription, "Necromancers turn the cold grammar of death into a weapon. Their necromancy spells strike with crueler force, drawing extra power from every die of damage when cast through the Necromancer spellbook." },
            { LocalizationIds.Mod.NecromancerBoneArmorClassCardDescription, "A Necromancer is never truly unguarded. Pale plates, splinters, and spectral ribs gather around them as they grow in power, forming a grim ward that hardens their defenses without slowing their spellcasting." },
            { LocalizationIds.Mod.EvokerArcaneName, "Arcanist" },
            { LocalizationIds.Mod.EvokerArcaneDescription, "Your blood hums with raw arcane resonance, shaping pure magical force into devastating expressions of power." },
            { LocalizationIds.Mod.EvokerAirName, "Stormcaller" },
            { LocalizationIds.Mod.EvokerAirDescription, "Lightning dances at your fingertips and thunder rolls in your wake." },
            { LocalizationIds.Mod.EvokerEarthName, "Vitriomancer" },
            { LocalizationIds.Mod.EvokerEarthDescription, "Your power manifests as virulent acid and caustic corruption." },
            { LocalizationIds.Mod.EvokerFireName, "Pyromancer" },
            { LocalizationIds.Mod.EvokerFireDescription, "Flame is your birthright, and your magic burns with unrestrained intensity." },
            { LocalizationIds.Mod.EvokerWaterName, "Glacialist" },
            { LocalizationIds.Mod.EvokerWaterDescription, "Frost answers your call, locking enemies in killing cold." },
            { LocalizationIds.Mod.EvokerScalingArcaneName, "Arcanist - Arcane Supremacy" },
            { LocalizationIds.Mod.EvokerScalingArcaneDescription, "Your grasp of arcane structure refines your destructive spells. You gain a +2 bonus to the Difficulty Class of Evocation spells cast from your Evoker spellbook per rank. Ranks increase at levels 1, 5, 9, 13, and 17." },
            { LocalizationIds.Mod.EvokerScalingAirName, "Stormcaller - Tempest Surge" },
            { LocalizationIds.Mod.EvokerScalingAirDescription, "You channel the growing wrath of the storm. Evocation spells cast from your Evoker spellbook that deal electricity damage gain +1 damage per die per rank. Ranks increase at levels 1, 5, 9, 13, and 17." },
            { LocalizationIds.Mod.EvokerScalingEarthName, "Vitriomancer - Corrosive Mastery" },
            { LocalizationIds.Mod.EvokerScalingEarthDescription, "Your corrosive magic intensifies with each milestone. Evocation spells cast from your Evoker spellbook that deal acid damage gain +1 damage per die per rank. Ranks increase at levels 1, 5, 9, 13, and 17." },
            { LocalizationIds.Mod.EvokerScalingFireName, "Pyromancer - Infernal Potency" },
            { LocalizationIds.Mod.EvokerScalingFireDescription, "Your flames burn with escalating fury. Evocation spells cast from your Evoker spellbook that deal fire damage gain +1 damage per die per rank. Ranks increase at levels 1, 5, 9, 13, and 17." },
            { LocalizationIds.Mod.EvokerScalingWaterName, "Glacialist - Glacial Dominion" },
            { LocalizationIds.Mod.EvokerScalingWaterDescription, "Your mastery of frost deepens with experience. Evocation spells cast from your Evoker spellbook that deal cold damage gain +1 damage per die per rank. Ranks increase at levels 1, 5, 9, 13, and 17." }
        };

        public static void Register(LocalizationTool localization)
        {
            foreach (var pair in Strings)
            {
                localization.Put(pair.Key, pair.Value);
            }
        }
    }
}
