using System;
using System.Linq;
using HarmonyLib;
using Kingmaker.Blueprints;
using Kingmaker.Blueprints.Items;
using Kingmaker.Blueprints.Loot;
using Kingmaker.UI.MVVM._VM.Loot;
using Kingmaker.View;
using Kingmaker.View.MapObjects;
using wotr_mod.Infrastructure;

namespace wotr_mod.Patches
{
    // Adds a scythe, shortsword, and rapier to the prologue's starting weapons chest
    // (the one right after the Kenabres invasion cutscene, where you meet Seelah).
    //
    // Its contents are a randomized roll, generated by some mechanism that never
    // triggered any of the container/inventory hooks tried (SetSource, AddItems,
    // ItemsCollection.Add) — but the placed object itself has a stable identity
    // (UniqueId "7d7c1267-7c09-4c30-9f00-ae3ddf013cce", named "Loot_1" in the editor),
    // confirmed identical across separate playthroughs/sessions. So instead of chasing
    // the generation mechanism, this hooks LootVM's constructor — built exactly when the
    // loot window opens, guaranteeing the container's contents are already fully
    // resolved by then — and injects into that specific container by UniqueId.
    [HarmonyPatch(typeof(LootVM))]
    [HarmonyPatch(MethodType.Constructor)]
    [HarmonyPatch(new[] { typeof(LootContextVM.LootWindowMode), typeof(EntityViewBase[]), typeof(Action) })]
    internal static class PrologueStartingWeaponsChestPatch
    {
        private const string TargetContainerUniqueId = "7d7c1267-7c09-4c30-9f00-ae3ddf013cce";

        private static readonly BlueprintGuid ScytheGuid =
            BlueprintGuid.Parse(GameBlueprintIds.Items.Scythe);

        private static void Prefix(EntityViewBase[] objects)
        {
            try
            {
                if (objects == null)
                {
                    return;
                }

                foreach (var entityViewBase in objects)
                {
                    if (entityViewBase?.Data?.UniqueId != TargetContainerUniqueId)
                    {
                        continue;
                    }

                    var lootPart = entityViewBase.Data.Get<InteractionLootPart>();
                    if (lootPart?.Loot == null)
                    {
                        continue;
                    }

                    if (lootPart.Loot.Items.Any(i => i?.Blueprint?.AssetGuid == ScytheGuid))
                    {
                        continue;
                    }

                    var standardScythe = BlueprintTool.Instance.Get<BlueprintItem>(GameBlueprintIds.Items.Scythe);
                    var shortsword = BlueprintTool.Instance.Get<BlueprintItem>(GameBlueprintIds.Items.Shortsword);
                    var rapier = BlueprintTool.Instance.Get<BlueprintItem>(GameBlueprintIds.Items.MasterworkRapier);
                    if (standardScythe == null || shortsword == null || rapier == null)
                    {
                        continue;
                    }

                    lootPart.AddItems(new[]
                    {
                        new LootEntry { Item = standardScythe, Count = 1 },
                        new LootEntry { Item = shortsword, Count = 1 },
                        new LootEntry { Item = rapier, Count = 1 }
                    });
                }
            }
            catch (Exception ex)
            {
                Main.Log($"Failed to add starting weapons to prologue chest: {ex}");
            }
        }
    }
}
