using System;
using System.Linq;
using HarmonyLib;
using Kingmaker;
using Kingmaker.Blueprints;
using Kingmaker.Blueprints.Items;
using Kingmaker.Blueprints.Loot;
using Kingmaker.Items;
using Kingmaker.UI.MVVM._VM.Loot;
using Kingmaker.View;
using Kingmaker.View.MapObjects;
using wotr_mod.Infrastructure;

namespace wotr_mod.Patches
{
    // Adds a scythe, shortsword, and rapier to the prologue's starting weapons chest
    // (the one right after the Kenabres invasion cutscene, where you meet Seelah).
    //
    // Its contents are a randomized roll, generated by some mechanism that never
    // triggered any of the container/inventory hooks tried (SetSource, AddItems,
    // ItemsCollection.Add) — but the placed object itself has a stable identity
    // (UniqueId "7d7c1267-7c09-4c30-9f00-ae3ddf013cce", named "Loot_1" in the editor),
    // confirmed identical across separate playthroughs/sessions. So instead of chasing
    // the generation mechanism, this hooks LootVM's constructor — built exactly when the
    // loot window opens, guaranteeing the container's contents are already fully
    // resolved by then — and injects into that specific container by UniqueId.
    [HarmonyPatch(typeof(LootVM))]
    [HarmonyPatch(MethodType.Constructor)]
    [HarmonyPatch(new[] { typeof(LootContextVM.LootWindowMode), typeof(EntityViewBase[]), typeof(Action) })]
    internal static class PrologueStartingWeaponsChestPatch
    {
        private const string TargetContainerUniqueId = "7d7c1267-7c09-4c30-9f00-ae3ddf013cce";
        private const string BrimorakHouseContainerUniqueId = "714fe373-791c-4df9-b468-9947f6ca0cac";

        private static readonly BlueprintGuid ScytheGuid =
            BlueprintGuid.Parse(GameBlueprintIds.Items.Scythe);
        private static readonly BlueprintGuid DaggerPlus1Guid =
            BlueprintGuid.Parse(GameBlueprintIds.Items.DaggerPlus1);
        private static readonly BlueprintGuid ScrollOfRemoveBlindnessGuid =
            BlueprintGuid.Parse(GameBlueprintIds.Items.ScrollOfRemoveBlindness);
        private static readonly BlueprintGuid BrimorakInHouseGuid =
            BlueprintGuid.Parse(GameBlueprintIds.AreaParts.KenabresBurningBrimorakInHouse);

        private static void Prefix(EntityViewBase[] objects)
        {
            try
            {
                if (objects == null)
                {
                    return;
                }

                AddBrimorakHouseRewards(objects);

                foreach (var entityViewBase in objects)
                {
                    if (entityViewBase?.Data?.UniqueId != TargetContainerUniqueId)
                    {
                        continue;
                    }

                    var lootPart = entityViewBase.Data.Get<InteractionLootPart>();
                    if (lootPart?.Loot == null)
                    {
                        continue;
                    }

                    if (lootPart.Loot.Items.Any(i => i?.Blueprint?.AssetGuid == ScytheGuid))
                    {
                        continue;
                    }

                    var standardScythe = BlueprintTool.Instance.Get<BlueprintItem>(GameBlueprintIds.Items.Scythe);
                    var shortsword = BlueprintTool.Instance.Get<BlueprintItem>(GameBlueprintIds.Items.Shortsword);
                    var rapier = BlueprintTool.Instance.Get<BlueprintItem>(GameBlueprintIds.Items.MasterworkRapier);
                    if (standardScythe == null || shortsword == null || rapier == null)
                    {
                        continue;
                    }

                    lootPart.AddItems(new[]
                    {
                        new LootEntry { Item = standardScythe, Count = 1 },
                        new LootEntry { Item = shortsword, Count = 1 },
                        new LootEntry { Item = rapier, Count = 1 }
                    });
                }
            }
            catch (Exception ex)
            {
                Main.Log($"Failed to add starting weapons to prologue chest: {ex}");
            }
        }

        private static void AddBrimorakHouseRewards(EntityViewBase[] objects)
        {
            if (Game.Instance?.CurrentlyLoadedAreaPart?.AssetGuid != BrimorakInHouseGuid)
            {
                return;
            }

            foreach (var entityViewBase in objects)
            {
                if (!LootWindowUtility.HasUniqueId(entityViewBase, BrimorakHouseContainerUniqueId))
                {
                    continue;
                }

                var lootPart = LootWindowUtility.GetLootPart(entityViewBase);
                if (lootPart?.Loot == null)
                {
                    continue;
                }

                var dagger = BlueprintTool.Instance.Get<BlueprintItem>(GameBlueprintIds.Items.DaggerPlus1);
                var scroll = BlueprintTool.Instance.Get<BlueprintItem>(GameBlueprintIds.Items.ScrollOfRemoveBlindness);
                if (dagger == null || scroll == null)
                {
                    continue;
                }

                EnsureLootItemCount(lootPart.Loot, dagger, DaggerPlus1Guid, 2);
                EnsureLootItemCount(lootPart.Loot, scroll, ScrollOfRemoveBlindnessGuid, 2);
            }
        }

        private static void EnsureLootItemCount(
            ItemsCollection loot,
            BlueprintItem item,
            BlueprintGuid itemGuid,
            int count)
        {
            var existingItem = loot.Items.FirstOrDefault(existing => existing?.Blueprint?.AssetGuid == itemGuid);
            if (existingItem != null)
            {
                if (existingItem.Count < count)
                {
                    existingItem.SetCount(count);
                }

                existingItem.Identify();
                return;
            }

            loot.Add(item, count, true, createdItem =>
            {
                createdItem.SetCount(count);
                createdItem.Identify();
            });
        }
    }
}
